(rule
 (copy ../main.bc.js hazel.js))

(rule
 (copy ../worker.bc.js worker.js))

(rule
 (copy ../furlMain.bc.js furl.js))

(rule
 (targets bundled.js)
 (deps prebundle.js)
 (action
  (run
   %{project_root}/node_modules/esbuild/bin/esbuild
   prebundle.js
   --bundle
   --outfile=bundled.js)))

(rule
 (copy ../../../furl/interactions/wire.js furl-wire.js))
